### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by impredicative** [facebookresearch/DME#1]
The readme mentions Python 2 which is [almost obsolete](https://pythonclock.org/). Please upgrade to and formally support Python 3.7 which is the current version. Python 2 code cannot be readily integrated into modern codebases.

**Comment by BSalita** [comment]
What the man said.

**Comment by kahne** [comment]
@impredicative @BSalita 

Yeah, we plan to support Python 3 in the near future. Please stay tuned.

**Comment by kahne** [comment]
Please pull the latest code to get Python 3 support.
