### ISSUE TITLE
Link to Arxiv

### ISSUE THREAD

**Issue by impredicative** [facebookresearch/DME#2]
I see that the readme links to the corresponding Arxiv paper. Please update the link to point to the HTML abstract, i.e. to https://arxiv.org/abs/1804.07983 , and not to the PDF. Some readers merely want to read the abstract only. If they want the PDF, they can easily click on the PDF link on the Arxiv HTML page.

**Comment by douwekiela** [comment]
Thanks. Fixed by https://github.com/facebookresearch/DME/commit/20cb65f5998b740703e8b29682ce903cafbc907c
