### ISSUE TITLE
SNLI checkpoint incompatible

### ISSUE THREAD

**Issue by aalok-sathe** [facebookresearch/DME#8]
I believe the checkpoint for DME you provide is incompatible with the model that is constructed using SNLI data for task=snli. Mainly, the vocabulary somehow mismatches and doesn't allow the checkpoint's outermost layers, for embeddings, to be loaded into the model so constructed. Of course, we could train our model using the script, but just thought I should mention this in case more people are facing the same issue.

**Comment by aalok-sathe** [comment]
Thanks for making the code public, BTW! this repo is helpful!

**Comment by kahne** [comment]
Hi @aalok-sathe ! 

Sorry for late reply. I am trying to reproduce the issue you reported but failed to see the same errors. Do you mind sharing the exact arguments you were using? Thank you!

**Comment by kahne** [comment]
@aalok-sathe  I will close this issue for now. Please feel free to file a new issue when you have more details. Thank you!

**Comment by yrchen92** [comment]
@kahne Thanks for making the code public! 
However, I have the same issue about loading SNLI checkpoint. When running the snli script, I got the error below:
Traceback (most recent call last):
  File "train.py", line 270, in <module>
    main()
  File "train.py", line 203, in main
    early_stopper) + 1
  File "train.py", line 54, in resume_from_checkpoint
    model.load_state_dict(checkpoint['model_state_dict'])
  File "/data/data1/yirche/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LanguageInferenceModel:
        size mismatch for encoder.embedder.embedders.fasttext.embedder.weight: copying a param with shape torch.Size([37262, 300]) from checkpoint, the shape in current model is torch.Size([37261, 300]).
        size mismatch for encoder.embedder.embedders.glove.embedder.weight: copying a param with shape torch.Size([37262, 300]) from checkpoint, the shape in current model is torch.Size([37261, 300]).

But I don't know what's the missing word.  My env:
python=3.6.8
torch=1.0.0
spacy=2.1.3
torchtext=0.2.3

Thanks again
